[program:adasi-sto-worker]
process_name=%(program_name)s_%(process_num)02d

; Ganti /var/www/adasi_sto dengan absolute path alamat folder aplikasi di server Anda
command=php /var/www/adasi_sto/artisan queue:work database --sleep=3 --tries=3 --max-time=3600

autostart=true
autorestart=true
stopasgroup=true
killasgroup=true

; Ganti www-data dengan user web server Anda (bisa www-data, ubuntu, root, dsb)
user=www-data

numprocs=1
redirect_stderr=true

; Pastikan folder logs ini bisa ditulis (writable)
stdout_logfile=/var/www/adasi_sto/storage/logs/worker.log
stopwaitsecs=3600
